### ISSUE TITLE
Implement CLI method for `getinfo`

### ISSUE THREAD

**Issue by t-bast** [ACINQ/eclair-cli#5]
Implement the CLI method to call eclair's `getinfo` API: https://acinq.github.io/eclair/#getinfo
This requires setting up the architecture for making HTTP calls, parsing the results and handling errors.

**Comment by claddyk** [comment]
The recent push I did(on my [fork](https://github.com/claddyk/eclair-cli/tree/getinfo)) is not building.
The deserialization in the [eclair-client](https://github.com/claddyk/eclair-cli/blob/getinfo/src/nativeMain/kotlin/eclairClient.kt) is not working even though I did the right imports, as well as followed the correct syntax(like we did in [mempool-client](https://github.com/claddyk/MempoolCLI/blob/main/src/main/kotlin/Mempool.kt).

```bash
import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.engine.cio.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.request.*
import io.ktor.serialization.kotlinx.json.*
import kotlinx.serialization.json.Json

interface IEclairClient {
    suspend fun getInfo(): Result<EclairInfo>
}

class EclairClient: IEclairClient {
    private val httpClient = HttpClient(CIO) {
        install(ContentNegotiation) {
            json(Json {
                ignoreUnknownKeys = true
                prettyPrint = true
                isLenient = true
            })
        }
    }

    override suspend fun getInfo(): Result<EclairInfo> {
        val response = httpClient.get("https://localhost:8080/getinfo")
        return response.runCatching {
            body<EclairInfo>()
        }
    }
}
```

**Comment by claddyk** [comment]
Update: above is fixed.
The correct version for kotlinx-serialization for kotlin/native is implementation 1.5.1

**Comment by claddyk** [comment]
To create the option for the user to enter the password while running the eclair-cli, there are 2 options
- In the first option, I think we can read the password from the eclair.conf file. But there might be security issues in this case. We can use (reader function)[https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-reader/] for this.
- The other option is to prompt the user for it. The way to go ahead in this is by using (readLine())[https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/read-line.html] function. But this would echo the password when the user types it. This could be solved if we use readPassword function from java, but maybe we want to write pure Kotlin code.

Which option would be suitable(as I see compromises in every option)?
Please let me know if I am missing out something.

**Comment by t-bast** [comment]
We definitely should **not** force the user to write his password every time they make a request by prompting them, this is unusable in practice.

We shouldn't read from the `eclair.conf` file either, it may not have read permissions for the user using the `eclair-cli`.

The solution is much simpler than that: we should just make the password (and the url of the eclair node API) arguments of every commands provided by the `eclair-cli`. Then the user can simply define an alias where those values are filled by default with their password, something like:

```sh
alias my-eclair-cli='eclair-cli --password <password> --host <url_of_the_eclair_api>'
```

**Comment by claddyk** [comment]
Okay, can you please elaborate on how does eclair-cli does authentication.
When I open the http://localhost:8080 physically, I'm prompted for this
![image](https://github.com/ACINQ/eclair-cli/assets/37688684/c42ef11a-ec00-4729-a445-46c3f476ed04)
The user is empty, and the password is password. 
I get the response:
```
{
  "error" : "The requested resource could not be found."
}
```

**Comment by t-bast** [comment]
It doesn't make sense to use it in a browser, just is an API so it must be queried directly over HTTP.
You can see exactly how it is done with the current `eclair-cli`: https://github.com/ACINQ/eclair/blob/master/eclair-core/eclair-cli
The password is simply url-encoded like a standard web form.

**Comment by t-bast** [comment]
You should use the existing CLI to figure out what happens under the hood. You can simply modify the `eclair-cli` script provided by eclair to make `curl` print verbose information:

```sh
eval curl "--user $auth --verbose --show-error -X POST -H \"Content-Type: application/x-www-form-urlencoded\" $api_payload $api_url/$api_endpoint" | jq -r "$jq_filter"
```

Instead of:

```sh
eval curl "--user $auth --silent --show-error -X POST -H \"Content-Type: application/x-www-form-urlencoded\" $api_payload $api_url/$api_endpoint" | jq -r "$jq_filter"
```

If you do that, `curl` will print the exact HTTP request it's sending and the response it's receiving.
You'll see that the request contains an `Authorization` header, which contains the user name and password in base64 encoding.
